# settings.yaml file
# This file contains all settings for a model to run.

mode: train              # string - 'train' if you want to train, 'predict' if you want to predict (only two options possible) (do not use quotes)
path_trained_folder: weights_only_full_trained        #string - just a folder name where fully trained nets are located
filename_trained_weights: resnet_single_newtr_last_last_weights_only.h5   #string - filename of trained network weights

model_name: first_model     # string
num_chunks: 500             # int
chunk_size: 1280            # int     was 1280 originally
batch_size: 64              # int
num_batch_augm: 20          # int
img_rows: 101               # int
img_cols: 101               # int
root_dir_models: models     # string

#other parameters
nbands: 1                   # number of color channels you want to use.
normalize: True             # boolean - Normalize the images to max of 255 (valid for single-band only)
augm_pred: False            # boolean
learning_rate: 0.0001       # float
resize: False               # float

#more parameters
range_min: 0.02             # float
range_max: 0.30             # float

#more parameters
buffer_size: 10             # int
avg_img: 0                  # int

#default augmentation parameters
zoom_range_min: 0.90909090909   # float     (this value here is: 1.0/1.1)
zoom_range_max: 1.0             # float
rotation_range_min: 0           # int
rotation_range_max: 180         # int range = [0; 360]
shear_range_min: 0              # int
shear_range_max: 0              # int
translation_range_min: -4       # int - can be negative - should be negative :) - like "-4"
translation_range_max: 4        # int - preferably positive absolute(translation_range_min) - like 4
do_flip: True                   # boolean (True or False)


# plot parameters
chunk_plot_interval: 1          # int - Every x chunks a plot of loss will be made, where x is this variable